#!/bin/bash

# generate_doc.sh
#
# Generate a Markdown reference of a protobuf API using the Docker image from:
# https://github.com/pseudomuto/protoc-gen-doc, and place it into the project's
# 'doc' subdirectory.
#
# Usage:
#   generate_doc

set -euo pipefail

abs_project_dir="$(realpath -- "$(dirname -- "${0}")/..")"

cidfile="${CIDFILE:-.cidfile}"

function stop_docker_container
{
    if [[ -f ${cidfile} ]]; then
        rm "${cidfile}"
    fi
    if [[ -n ${cid:-} ]]; then
        docker stop --time 0 "${cid}"
    fi
}

docker_wd=/opt/techmo/asr-api
docker run --detach --interactive --rm \
    --cidfile "${cidfile}" \
    --entrypoint sleep \
    --volume "${abs_project_dir}:${docker_wd}:ro" \
    pseudomuto/protoc-gen-doc \
    infinity
cid="$(< "${cidfile}")"

trap stop_docker_container EXIT

protoc_options=(
    --proto_path="./proto"
)

api_version="${API_VERSION:-legacy}"
api_dir="${API_DIR:-./proto/techmo/asr/api/${api_version}}"

readarray -d '' protos < <(
    docker exec --workdir "${docker_wd}" "${cid}" \
        find "${api_dir}" -name '*.proto' -print0
)

read -ra protoc_options <<< "${PROTOC_OPTIONS-${protoc_options[@]}}"
read -ra protos <<< "${PROTOS-${protos[@]}}"

api_docfile="${API_DOCFILE:-techmo-asr-api-${api_version}-autogenerated.md}"

docker exec \
    --workdir "${docker_wd}" \
    "${cid}" \
    protoc \
    --plugin=protoc-gen-doc=/usr/bin/protoc-gen-doc \
    --doc_opt="markdown,${api_docfile}" \
    --doc_out=/out \
    "${protoc_options[@]}" \
    "${protos[@]}"

mkdir --parents "${abs_project_dir}/doc"
docker cp "${cid}:/out/${api_docfile}" "${abs_project_dir}/doc/${api_docfile}"

# Fix the quotation marks in the comments that get replaced with '&#34;'.
sed --in-place --expression='s,&#34;,",g' "${abs_project_dir}/doc/${api_docfile}"
